root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - packages/*/tsconfig.json

plugins:
  - '@typescript-eslint'
  - import

settings:
  import/extensions: [.ts]
  import/parsers:
    '@typescript-eslint/parser': [.ts]
  import/resolver:
    typescript:
      project:
        - packages/*/tsconfig.json
  import/internal-regex: ^@fbe/

extends:
  - eslint:recommended
  - .eslint.base.yml
  # Turn off eslint rules that conflict with typescript-eslint
  - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
  # - plugin:@typescript-eslint/strict
  - .eslint.typescript.yml
  - .eslint.import.yml
