printWidth: 100 # default: 80, TODO: consider removing
tabWidth: 4 # default: 2
semi: false # default: true
singleQuote: true # default: false, TODO: consider removing
trailingComma: es5 # default: all
arrowParens: avoid # default: always, TODO: consider removing

overrides:
  - files: '*.yml'
    options:
      tabWidth: 2 # default
