[package]
name = "fbe_backend"
version = "0.1.0"
edition = "2018"

[profile.dev]
opt-level = 2
debug-assertions = true

[features]
dev = ["dotenv", "listenfd"]

[dependencies]
image = "0.23.4"
actix-rt = "1.1.1"
actix-web = "3.0.0-alpha.2"
actix-http = "2.0.0-alpha.3"
futures = "0.3.5"
bytes = "0.5"
serde = { version = "1.0.110", features = ["derive"] }
serde_json = "1.0.53"
reqwest = { version = "0.10", features = ["json", "stream"] }
tokio = { version = "0.2", features = ["full"] }
regex = "1.3.7"
globset = "0.4.5"
async-recursion = "0.3.1"
lazy_static = "1.4.0"
async-compression = { version = "0.3.4", features = ["stream", "lzma"] }
indicatif = "0.14.0"
listenfd = { version = "0.3", optional = true }
dotenv = { version = "0.15.0", optional = true }
seahash = "4.0.0"
# async-tar = "0.1.1"
# tokio-tar = "0.2.0"
