[package]
name = "factorio_data_exporter"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
futures = "0.3.31"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
reqwest = { version = "0.12.9", features = ["json", "stream"] }
tokio = { version = "1.42.0", features = ["full"] }
regex = "1.11.1"
globset = "0.4.15"
async-recursion = "1.1.1"
lazy_static = "1.5.0"
async-compression = { version = "0.4.18", features = ["tokio", "lzma"] }
indicatif = "0.17.9"
tokio-stream = "0.1.17"
tokio-tar = "0.3.1"
tokio-util = { version = "0.7.13", features = ["io"] }
hyper-staticfile = "0.10.1"
hyper = { version = "1.5.1", features = ["http1", "server"] }
hyper-util = { version = "0.1.10", features = ["tokio"] }
http = "1.2.0"
zip = "2.2.1"
dotenvy = "0.15.7"